version: "3.8"

services:
  myfinance_app:
    container_name: myfinance_app
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8002:8002"
    volumes:
      - .:/app
    env_file:
      - envs/.env
    command:  ["gunicorn", "--bind", ":8002", "--workers", "2", "core.wsgi"]
